version: "3"
services:
  api-gateway:
    image: sarrahmanme/api-gateway
    ports:
      - "80:80"
    container_name: api-gateway
    depends_on:
      - users-service
      - supliers-service
      - webstore-service
      - analysis-service
      - products-command-service
      - products-query-service
      - partners-service
      - messaging-service
    networks:
      - tokokeramik-network

  users-service:
    image: sarrahmanme/users-service
    container_name: users-service
    networks:
      - tokokeramik-network
    environment:
      - DB_HOST=10.0.2.40

  supliers-service:
    image: sarrahmanme/supliers-service
    container_name: supliers-service
    networks:
      - tokokeramik-network
    environment:
      - DB_HOST=10.0.2.40

  webstore-service:
    image: sarrahmanme/webstore-service
    container_name: webstore-service
    networks:
      - tokokeramik-network
    environment:
      - DB_HOST=10.0.2.40
      - PARTNERS_SERVICE=http://partners-service:5001

  analysis-service:
    image: sarrahmanme/analysis-service
    container_name: analysis-service
    networks:
      - tokokeramik-network
    environment:
      - MONGO_HOST=10.0.2.40
      - RABBITMQ_HOST=amqp://sarrahman:@124HM4n190919@10.0.2.40:5672

  products-command-service:
    image: sarrahmanme/products-command-service
    container_name: products-command-service
    networks:
      - tokokeramik-network
    environment:
      - DB_HOST=10.0.2.40
      - RABBITMQ_HOST=amqp://sarrahman:@124HM4n190919@10.0.2.40:5672

  products-query-service:
    image: sarrahmanme/products-query-service
    container_name: products-query-service
    networks:
      - tokokeramik-network
    environment:
      - MONGO_HOST=10.0.2.40
      - SUPLIERS_SERVICE=http://supliers-service:5003
      - RABBITMQ_HOST=amqp://sarrahman:@124HM4n190919@10.0.2.40:5672

  partners-service:
    image: sarrahmanme/partners-service
    container_name: partners-service
    networks:
      - tokokeramik-network
    environment:
      - DB_HOST=10.0.2.40
      - RABBITMQ_HOST=amqp://sarrahman:@124HM4n190919@10.0.2.40:5672

  messaging-service:
    image: sarrahmanme/messaging-service
    container_name: messaging-service
    networks:
      - tokokeramik-network
    environment:
      - RABBITMQ_HOST=amqp://sarrahman:@124HM4n190919@10.0.2.40:5672

networks:
  tokokeramik-network:
    driver: bridge
