version: "3"
services:
  api-gateway:
    image: sarrahmanme/api-gateway:arm64-0.0.9
    ports:
      - "80:80"
    container_name: api-gateway
    depends_on:
      - products-service
      - users-management-service
      - suplier-service
      - mitra-service
      - finance-service
      - membership-service
      - webstore-service
      - auth-service
      - message-service
      - ai-service
    networks:
      - sarrahman-bangunan-network

  configuration-service:
    image: sarrahmanme/configuration-service:arm64-0.2.1
    container_name: configuration-service
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=13.213.30.75
      - DB_NAME=sarrahman-bangunan
      - REDIS_HOST=13.213.30.75

  products-service:
    image: sarrahmanme/products-service:arm64-0.2.1
    container_name: products-service
    depends_on:
      - configuration-service
    networks:
      - sarrahman-bangunan-network
    environment:
      - MONGO_URI=mongodb+srv://sarrahmanme:124HM4n190919@cluster0.jujuafr.mongodb.net/?retryWrites=true&w=majority
      - REDIS_HOST=13.213.30.75

  users-management-service:
    image: sarrahmanme/users-management-service:arm64-0.2.1
    container_name: users-management-service
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=13.213.30.75
      - DB_NAME=sarrahman-bangunan
      - RABBITMQ_HOST=amqp://sarrahman:@124HM4n190919@13.213.30.75

  suplier-service:
    image: sarrahmanme/suplier-service:arm-0.2.1
    container_name: suplier-service
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=13.213.30.75
      - DB_NAME=sarrahman-bangunan
      - RABBITMQ_HOST=amqp://sarrahman:@124HM4n190919@13.213.30.75

  mitra-service:
    image: sarrahmanme/mitra-service:arm64-0.2.2
    container_name: mitra-service
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=13.213.30.75
      - DB_NAME=sarrahman-bangunan
      - RABBITMQ_HOST=amqp://sarrahman:@124HM4n190919@13.213.30.75

  finance-service:
    image: sarrahmanme/finance-service:arm64-0.2.1
    container_name: finance-service
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=13.213.30.75
      - DB_NAME=sarrahman-bangunan
      - RABBITMQ_HOST=amqp://sarrahman:@124HM4n190919@13.213.30.75

  membership-service:
    image: sarrahmanme/membership-service:arm64-0.2.1
    container_name: membership-service
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=13.213.30.75
      - REDIS_HOST=13.213.30.75
      - DB_NAME=sarrahman-bangunan
      - MITRA_API_SERVICE=http://mitra-service:5006
      - FINANCE_API_SERVICE=http://finance-service:5007
      - RABBITMQ_HOST=amqp://sarrahman:@124HM4n190919@13.213.30.75

  webstore-service:
    image: sarrahmanme/webstore-service:arm64-0.2.1
    container_name: webstore-service
    depends_on:
      - configuration-service
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=13.213.30.75
      - DB_NAME=sarrahman-bangunan
      - MITRA_API_SERVICE=http://mitra-service:5006
      - REDIS_HOST=13.213.30.75
      - RABBITMQ_HOST=amqp://sarrahman:@124HM4n190919@13.213.30.75

  auth-service:
    image: sarrahmanme/auth-service:arm64-0.2.3
    container_name: auth-service
    networks:
      - sarrahman-bangunan-network
    environment:
      - REDIS_HOST=13.213.30.75
      - USER_MANAGEMENT_SERVICE=http://users-management-service:5002
      - MITRA_SERVICE=http://mitra-service:5006
      - RABBITMQ_HOST=amqp://sarrahman:@124HM4n190919@13.213.30.75

  ai-service:
    image: sarrahmanme/ai-service:arm64-0.0.7
    container_name: ai-service
    networks:
      - sarrahman-bangunan-network

  maps-service:
    image: sarrahmanme/maps-service:arm64-0.0.1
    container_name: maps-service
    networks:
      - sarrahman-bangunan-network

  message-service:
    image: sarrahmanme/message-service:arm64-0.0.4
    container_name: message-service
    networks:
      - sarrahman-bangunan-network
    environment:
      - RABBITMQ_HOST=amqp://sarrahman:@124HM4n190919@13.213.30.75

networks:
  sarrahman-bangunan-network:
    driver: bridge
