version: "3"
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    container_name: api-gateway
    depends_on:
      - products-service
      - users-management-service
      - suplier-service
      - mitra-service
      - finance-service
      - membership-service
      - webstore-service
      - auth-service
      - ai-service
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - sarrahman-bangunan-network

  products-service:
    build:
      context: ./products-service
      dockerfile: Dockerfile
    container_name: products-service
    depends_on:
      - mongodb
    networks:
      - sarrahman-bangunan-network
    environment:
      - MONGO_URI=mongodb://mongodb/product-service

  users-management-service:
    build:
      context: ./users-management-service
      dockerfile: Dockerfile
    container_name: users-management-service
    depends_on:
      - postgres
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=postgres
      - DB_NAME=sarrahman-bangunan

  suplier-service:
    build:
      context: ./suplier-service
      dockerfile: Dockerfile
    container_name: suplier-service
    depends_on:
      - postgres
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=postgres
      - DB_NAME=sarrahman-bangunan

  mitra-service:
    build:
      context: ./mitra-service
      dockerfile: Dockerfile
    container_name: mitra-service
    depends_on:
      - postgres
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=postgres
      - DB_NAME=sarrahman-bangunan

  finance-service:
    build:
      context: ./finance-service
      dockerfile: Dockerfile
    container_name: finance-service
    depends_on:
      - postgres
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=postgres
      - DB_NAME=sarrahman-bangunan

  membership-service:
    build:
      context: ./membership-service
      dockerfile: Dockerfile
    container_name: membership-service
    depends_on:
      - postgres
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=postgres
      - DB_NAME=sarrahman-bangunan
      - MITRA_API_SERVICE=http://mitra-service:5006
      - FINANCE_API_SERVICE=http://finance-service:5007

  webstore-service:
    build:
      context: ./webstore-service
      dockerfile: Dockerfile
    container_name: webstore-service
    depends_on:
      - postgres
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=postgres
      - DB_NAME=sarrahman-bangunan
      - MITRA_API_SERVICE=http://mitra-service:5006

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    networks:
      - sarrahman-bangunan-network
    environment:
      - USER_MANAGEMENT_SERVICE=http://users-management-service:5002
      - MITRA_SERVICE=http://mitra-service:5006

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: ai-service
    networks:
      - sarrahman-bangunan-network

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@124HM4n190919
      - POSTGRES_DB=sarrahman-bangunan
    container_name: postgres
    volumes:
      - ./postgres/backup:/pg-backup
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - sarrahman-bangunan-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=product-service
    container_name: mongodb
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/backup:/mongo-backup
    networks:
      - sarrahman-bangunan-network

networks:
  sarrahman-bangunan-network:
    driver: bridge
