version: "3"
services:
  api-gateway:
    image: sarrahmanme/api-gateway:0.0.5
    ports:
      - "80:80"
    container_name: api-gateway
    depends_on:
      - products-service
      - users-management-service
      - suplier-service
      - mitra-service
      - finance-service
      - membership-service
      - webstore-service
      - auth-service
      - message-service
      - ai-service
    networks:
      - sarrahman-bangunan-network

  products-service:
    image: sarrahmanme/products-service:0.0.5
    container_name: products-service
    networks:
      - sarrahman-bangunan-network
    environment:
      - MONGO_URI=mongodb+srv://sarrahmanme:124HM4n190919@cluster0.jujuafr.mongodb.net/?retryWrites=true&w=majority
      - ALLOWED_DOMAINS=http://localhost:3001,http://localhost:3000,http://localhost:3002,https://testing-webstore.netlify.app,https://admin.tokokeramik.com,https://www.tokokeramik.com,https://tokokeramik.com

  users-management-service:
    image: sarrahmanme/users-management-service:0.0.5
    container_name: users-management-service
    depends_on:
      - rabbitmq
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=3.1.204.153
      - DB_NAME=sarrahman-bangunan

  suplier-service:
    image: sarrahmanme/suplier-service:0.0.5
    container_name: suplier-service
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=3.1.204.153
      - DB_NAME=sarrahman-bangunan

  mitra-service:
    image: sarrahmanme/mitra-service:0.0.5
    container_name: mitra-service
    depends_on:
      - rabbitmq
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=3.1.204.153
      - DB_NAME=sarrahman-bangunan

  finance-service:
    image: sarrahmanme/finance-service:0.0.5
    container_name: finance-service
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=3.1.204.153
      - DB_NAME=sarrahman-bangunan

  membership-service:
    image: sarrahmanme/membership-service:0.0.5
    container_name: membership-service
    depends_on:
      - rabbitmq
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=3.1.204.153
      - DB_NAME=sarrahman-bangunan
      - MITRA_API_SERVICE=http://mitra-service:5006
      - FINANCE_API_SERVICE=http://finance-service:5007

  webstore-service:
    image: sarrahmanme/webstore-service:0.0.5
    container_name: webstore-service
    networks:
      - sarrahman-bangunan-network
    environment:
      - DB_HOST=3.1.204.153
      - DB_NAME=sarrahman-bangunan
      - MITRA_API_SERVICE=http://mitra-service:5006

  auth-service:
    image: sarrahmanme/auth-service:0.0.11
    container_name: auth-service
    networks:
      - sarrahman-bangunan-network
    depends_on:
      - rabbitmq
    environment:
      - USER_MANAGEMENT_SERVICE=http://users-management-service:5002
      - MITRA_SERVICE=http://mitra-service:5006

  ai-service:
    image: sarrahmanme/ai-service:0.0.5
    container_name: ai-service
    networks:
      - sarrahman-bangunan-network

  message-service:
    image: sarrahmanme/message-service:0.0.1
    container_name: message-service
    depends_on:
      - rabbitmq
    networks:
      - sarrahman-bangunan-network

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    container_name: rabbitmq
    networks:
      - sarrahman-bangunan-network
    environment:
      - RABBITMQ_DEFAULT_USER=sarrahman
      - RABBITMQ_DEFAULT_PASS=@124HM4n190919

networks:
  sarrahman-bangunan-network:
    driver: bridge
